{% set name = "ipumspy" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47451182cf0d140cd5d98ff911aa2691f6ad759cd171e99dbfad5a8a363a621b

build:
  number: 0
  entry_points:
    - ipums = ipumspy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=1.4

  run:
    - click >=8.0.0
    - pandas >=2.2.3,<3.0.0
    - numpy >2.0.0,<3.0.0
    - pyarrow >=18.1.0
    - python >={{ python_min }}
    - pyyaml >=6.0.0,<7.0.0
    - requests >=2.26.0,<3.0.0
    - importlib-metadata >=4.13.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipumspy
    - ipumspy.api
  commands:
    - ipums --help

about:
  home: The package home page
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: A collection of tools for working with IPUMS data
  doc_url: https://ipumspy.readthedocs.io/en/latest/
  dev_url:

extra:
  recipe-maintainers:
    - renae-r
    - ipums
