{% set name = "ipumspy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba16acc512a2a29ae211031eea7abd17b817b7cf142335a6e0bd2b6f4e26861b

build:
  number: 1
  entry_points:
    - ipums = ipumspy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - poetry >=1.4

  run:
    - click >=8.0.0
    - pandas >=1.5.2,<2.0.0
    - pyarrow >=10.0.0
    - python >=3.8
    - pyyaml >=5.4.1,<6.0.0
    - requests >=2.26.0,<3.0.0
    - chardet >=5.1.0
    - importlib-metadata >=4.13.1
    - beautifulsoup4 >=4.11.1

test:
  imports:
    - ipumspy
    - ipumspy.api
  commands:
    - ipums --help

about:
  home: The package home page
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: A collection of tools for working with IPUMS data
  doc_url: https://ipumspy.readthedocs.io/en/latest/
  dev_url:

extra:
  recipe-maintainers:
    - renae-r
    - ipums
